config/routes.rb
Rails.application.routes.draw do
  
  resources :countries
  
  root "countries#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: { strict: true }
  validates :name_confirmation, presence: true
  validates :capital_city , uniqueness: true
  validates :population, length: { in: 6..12 }
  after_create -> { puts "Congratulations!" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
  end 
 
  def new
    @country = Country.new 
  end
  def create
    @country = Country.new(param_country)
    if @country.save
      flash[:notice] = "Data created successfully!"
      redirect_to countries_path
    else 
      render 'new'
    end
  end
  def show
    @country = Country.find(params[:id])
  end
  def edit
    @country = Country.find(params[:id])
  end
  def update
    @country = Country.find(params[:id])
    @country.update(param_country)
    redirect_to countries_path
  end
  def destroy
    @country = Country.find(params[:id])
    @country.destroy 
    redirect_to countries_path
  end 
  private
    def param_country
      params.require(:country).permit(:name, :capital_city, :population)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/edit.html.erb
<h2> You Can Edit Your Information.</h2>

<%=form_for (@country) do |c| %>
  <%=c.label :name, "Country Name" %>
  <%=c.text_field :name %>
  <br> <br>
  <%=c.label :name, "Confirm Country Name" %>
  <%=c.text_field :name_confirmation %>
  <br> <br>
  <%=c.label :capital_city, "Capital City" %>
  <%=c.text_field :capital_city %>
  <br> <br>
  <%=c.label :population, "Population" %>
  <%=c.text_field :population %>
  <br> <br>
  <%=c.submit%>
<% end%>

app/views/countries/index.html.erb
<h3>List of available Countries.</h3>
<a href = "/countries/new" >Add New</a>
<% @countries.each do |country|%>
  <h2>ID : <%=country.id%></h2>
  <h3>Country Name : <%=country.name%> </h3>
  <h3>Capital City : <%=country.capital_city%></h3>
  <h3>Country's Population : <%=country.population%></h3>
  <%=link_to "Show Data", country_path(country.id) %>
 
  <br>
<% end %>

app/views/countries/new.html.erb
<h3>Add a Country.</h3>
<%=form_with model: (@country) do |c|%>
  <%=c.label :name, "Country Name" %>
  <%=c.text_field :name %> 
  <br> <br>
  <%=c.label :name, "Confirm Country Name" %>
  <%=c.text_field :name_confirmation %>
  <br> <br>
  <%=c.label :capital_city, "Capital City" %>
  <%=c.text_field :capital_city %>
  
  <br> <br>
  <%=c.label :population, "Population" %>
  <%=c.text_field :population %>
  <br> <br>
  <%=c.submit%>
<% end%>

app/views/countries/show.html.erb
<h1>This is the data for the following country id </h1>
<h3>Your ID : <%=@country.id%> </h3>
<h3>Country Name : <%= @country.name %> </h3>
<h3>Capital City : <%= @country.capital_city %></h3>
<h3>Country's Population : <%= @country.population %></h3>
<a href = "/countries/<%= @country.id %>/edit" >Edit Your Data</a>
<br><br><br>
<%= button_to "Delete #{@country.name}",@country, method: "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Countries</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>